"""Add annotated_image_url to sessions

Revision ID: 911f786872ae
Revises: 43211ee444f4
Create Date: 2025-05-18 02:16:09.709559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911f786872ae'
down_revision: Union[str, None] = '43211ee444f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('annotated_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'annotated_image_url')
    # ### end Alembic commands ###
